// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCneYryg8BSGi_LjnE8Y_ceWqIilfimSDA',
    appId: '1:1016474955951:web:8d3ac8dcd4c9dc3e02e45a',
    messagingSenderId: '1016474955951',
    projectId: 'chatapp2024-30077',
    authDomain: 'chatapp2024-30077.firebaseapp.com',
    storageBucket: 'chatapp2024-30077.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFZLkGmO97YW7aYvpcEqGb-2LA6hQbrzk',
    appId: '1:1016474955951:android:5daac5b1d6d3a33702e45a',
    messagingSenderId: '1016474955951',
    projectId: 'chatapp2024-30077',
    storageBucket: 'chatapp2024-30077.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiarCQl1_kTEKjBOL1G-jGp3lR21A8VFw',
    appId: '1:1016474955951:ios:a74af04a65df65b102e45a',
    messagingSenderId: '1016474955951',
    projectId: 'chatapp2024-30077',
    storageBucket: 'chatapp2024-30077.appspot.com',
    iosBundleId: 'com.tintran.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiarCQl1_kTEKjBOL1G-jGp3lR21A8VFw',
    appId: '1:1016474955951:ios:a74af04a65df65b102e45a',
    messagingSenderId: '1016474955951',
    projectId: 'chatapp2024-30077',
    storageBucket: 'chatapp2024-30077.appspot.com',
    iosBundleId: 'com.tintran.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCneYryg8BSGi_LjnE8Y_ceWqIilfimSDA',
    appId: '1:1016474955951:web:3568b80ffec615d802e45a',
    messagingSenderId: '1016474955951',
    projectId: 'chatapp2024-30077',
    authDomain: 'chatapp2024-30077.firebaseapp.com',
    storageBucket: 'chatapp2024-30077.appspot.com',
  );
}
